# Generated by Django 2.2.6 on 2019-10-26 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankedTier',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=255)),
                ('summoner_id', models.CharField(max_length=255)),
                ('puuid', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('server', models.CharField(choices=[('BR1', 'Brazil'), ('EUN1', 'EU Nordic & East'), ('EUW1', 'EU West'), ('JP1', 'Japan'), ('KR', 'Korea'), ('LA1', 'Latin America North'), ('LA2', 'Latin America South'), ('NA1', 'North America'), ('OC1', 'Oceania'), ('TR1', 'Turkey'), ('RU', 'Russia'), ('PBE1', 'Public Beta Environment')], max_length=255)),
                ('profile_icon_id', models.BigIntegerField(default=0)),
                ('summoner_level', models.IntegerField(default=1)),
                ('ranked_solo_league_id', models.CharField(blank=True, max_length=255)),
                ('ranked_solo_league_name', models.CharField(blank=True, max_length=255)),
                ('ranked_solo_hot_streak', models.BooleanField(default=False)),
                ('ranked_solo_wins', models.BigIntegerField(default=0)),
                ('ranked_solo_losses', models.BigIntegerField(default=0)),
                ('ranked_solo_veteran', models.BooleanField(default=False)),
                ('ranked_solo_rank', models.CharField(blank=True, max_length=255)),
                ('ranked_solo_inactive', models.BooleanField(default=False)),
                ('ranked_solo_fresh_blood', models.BooleanField(default=False)),
                ('ranked_solo_league_points', models.BigIntegerField(default=0)),
                ('ranked_flex_sr_league_id', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_sr_league_name', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_sr_hot_streak', models.BooleanField(default=False)),
                ('ranked_flex_sr_wins', models.BigIntegerField(default=0)),
                ('ranked_flex_sr_losses', models.BigIntegerField(default=0)),
                ('ranked_flex_sr_veteran', models.BooleanField(default=False)),
                ('ranked_flex_sr_rank', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_sr_inactive', models.BooleanField(default=False)),
                ('ranked_flex_sr_fresh_blood', models.BooleanField(default=False)),
                ('ranked_flex_sr_league_points', models.BigIntegerField(default=0)),
                ('ranked_flex_tt_league_id', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_tt_league_name', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_tt_hot_streak', models.BooleanField(default=False)),
                ('ranked_flex_tt_wins', models.BigIntegerField(default=0)),
                ('ranked_flex_tt_losses', models.BigIntegerField(default=0)),
                ('ranked_flex_tt_veteran', models.BooleanField(default=False)),
                ('ranked_flex_tt_rank', models.CharField(blank=True, max_length=255)),
                ('ranked_flex_tt_inactive', models.BooleanField(default=False)),
                ('ranked_flex_tt_fresh_blood', models.BooleanField(default=False)),
                ('ranked_flex_tt_league_points', models.BigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('ranked_flex_sr_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranked_flex_sr_tiers', to='Website.RankedTier')),
                ('ranked_flex_tt_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranked_flex_tt_tiers', to='Website.RankedTier')),
                ('ranked_solo_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranked_solo_tiers', to='Website.RankedTier')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summoners', to='Website.Profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='summoner',
            constraint=models.UniqueConstraint(fields=('summoner_id', 'server'), name='Unique Summoner Id by Server'),
        ),
        migrations.AddConstraint(
            model_name='summoner',
            constraint=models.UniqueConstraint(fields=('account_id', 'server'), name='Unique Account Id by Server'),
        ),
    ]
