# Generated by Django 2.2.6 on 2019-11-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20191104_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='gameDuration',
            new_name='game_duration',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gameId',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gameMode',
            new_name='game_mode',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gameType',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='gameVersion',
            new_name='game_version',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='mapId',
            new_name='map_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='platformId',
            new_name='platform_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='queueId',
            new_name='queue_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='seasonId',
            new_name='season_id',
        ),
    ]
