# Generated by Django 2.2.6 on 2019-11-08 02:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20191104_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(default=0)),
                ('total_gold', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_gold', models.IntegerField(default=0)),
                ('minions_killed', models.IntegerField(default=0)),
                ('position_x', models.IntegerField(null=True)),
                ('position_y', models.IntegerField(null=True)),
                ('xp', models.IntegerField(default=0)),
                ('jungle_minions_killed', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participant_Match', to='Website.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
                ('participant_id', models.IntegerField(null=True)),
                ('team_id', models.IntegerField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('victim_id', models.IntegerField(null=True)),
                ('creator_id', models.IntegerField(null=True)),
                ('killer_id', models.IntegerField(null=True)),
                ('assisting_participant_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('level_up_type', models.CharField(max_length=255, null=True)),
                ('ward_type', models.CharField(max_length=255, null=True)),
                ('building_type', models.CharField(max_length=255, null=True)),
                ('monster_type', models.CharField(max_length=255, null=True)),
                ('monster_sub_type', models.CharField(max_length=255, null=True)),
                ('tower_type', models.CharField(max_length=255, null=True)),
                ('lane_type', models.CharField(max_length=255, null=True)),
                ('skill_slot', models.IntegerField(null=True)),
                ('position_x', models.IntegerField(null=True)),
                ('position_y', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParticipantEvent_Match', to='Website.Match')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participantframe',
            constraint=models.UniqueConstraint(fields=('match', 'participant_id', 'timestamp'), name='Unique Participant & Timestamp by Match'),
        ),
    ]
