# Generated by Django 3.0.1 on 2019-12-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_auto_20191221_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
