# Generated by Django 3.0.1 on 2019-12-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_auto_20191226_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='types',
            new_name='type',
        ),
    ]
