# Generated by Django 3.0.1 on 2019-12-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_auto_20191226_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='postinteraction',
            old_name='type',
            new_name='post_interaction_type',
        ),
    ]
