# Generated by Django 3.0.1 on 2019-12-30 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0019_auto_20191229_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinterest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationinterest',
            name='early_access_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegistrationInterest_AccessCodes', to='Website.AccessCode'),
        ),
        migrations.AlterField(
            model_name='registrationinterest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegistrationInterest_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
