# Generated by Django 3.0.1 on 2019-12-30 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0020_auto_20191230_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='registration_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AccessCode_RegistrationInterests', to='Website.RegistrationInterest'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AccessCode_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
