# Generated by Django 3.0.1 on 2020-01-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_auto_20191230_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='post',
            name='promotion_division',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='promotion_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Post_Tiers', to='Website.RankedTier'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'Debug'), (2, 'Promotion'), (3, 'Shared Game')]),
        ),
    ]
