# Generated by Django 3.0.1 on 2020-01-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_auto_20200108_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Post_Matches', to='Website.Match'),
        ),
    ]
