# Generated by Django 3.0.1 on 2020-01-08 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0023_post_shared_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
